steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kibana-ci-service:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kibana-ci-service:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'kibana-ci-service',
        '--image',
        'gcr.io/$PROJECT_ID/kibana-ci-service:$COMMIT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
      ]

images: ['gcr.io/$PROJECT_ID/kibana-ci-service:$COMMIT_SHA']
